# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('redditusers', '0004_auto_20170303_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='redditcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redditusers.reddituser')),
            ],
        ),
    ]
