# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditusers', '0002_auto_20170303_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='redditusers',
        ),
        migrations.RenameField(
            model_name='redditusers',
            old_name='name',
            new_name='username',
        ),
    ]
