# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditusers', '0003_auto_20170303_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='redditusers',
            new_name='reddituser',
        ),
    ]
