# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditusers', '0005_reddituser_commentsafter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='commentsafter',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
